Jobbers/urls.py

from django.contrib import admin
from django.urls import path, include
from jobs.views import home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name= 'home'),
    path('jobs/', include('jobs.urls', namespace='jobs')),
    path('blog/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls'),)

]

jobs/urls.py
from django.urls import path
from jobs.views import jobs_view, about_view, Contact_Us, our_services, Add_Job, job_detail, Apply_Job

app_name = 'jobs'

urlpatterns = [ 

    path('add_job/', Add_Job.as_view(), name = 'add-job'),
    path('jobs_view/', jobs_view, name = 'job-view'),
    path('about_us/', about_view, name = 'about-view'),
    path('contact_us/', Contact_Us.as_view(), name = 'contact-us'),
    path('job_detail/<int:id>/', job_detail, name='job-detail'),
    path('services/', our_services, name = 'our-services'),
    path('apply/', Apply_Job.as_view(), name='apply'),
]



user/urls.py
from django.urls import path
from .views import UserRegistrationView

app_name = 'user'

urlpatterns = [

    path('register/', UserRegistrationView.as_view(), name='register'),

]

jobs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

JOB_TYPE = (
    ('Part Time', 'Part Time'),
    ('Full Time', 'Full Time'),
    ('Freelance', 'Freelance'),
)

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Any', 'Any'),
)

class Jobs(models.Model):
    username = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 50)
    company_name = models.CharField(max_length = 50)
    experience = models.CharField(max_length = 50)
    salary = models.CharField(max_length = 100, blank = True, null = True)
    description = models.TextField()
    job_location = models.CharField(max_length = 50)
    responsibilities = models.TextField()
    job_type = models.CharField(choices= JOB_TYPE, max_length = 50)
    gender = models.CharField(choices = GENDER, max_length = 50)
    total_vacancy = models.CharField(max_length = 10)
    application_deadline = models.DateTimeField()
    published_date = models.DateTimeField(default = timezone.now)
    image = models.ImageField(blank = True, null = True, upload_to = 'media')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home')

class ApplyJob(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    CV = models.FileField(null=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    Email = models.EmailField()
    subject = models.CharField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.first_name

user/models.py
from django.db import models



jobs/forms.py
from django import forms
from .models import Jobs, ApplyJob, Contact
from django.utils import timezone


JOB_TYPE = (
    ('Part Time', 'Part Time'),
    ('Full Time', 'Full Time'),
    ('Freelance', 'Freelance'),
)

GENDER = (
    ('Male', 'Male'),
    ('Female', 'Female'),
    ('Any', 'Any'),
)

class JobForm(forms.ModelForm):

    class Meta:
        model = Jobs
        fields = ('username','title', 'company_name', 'job_location', 'experience', 'salary',
        'description','job_type', 'gender', 'total_vacancy', 'responsibilities', 'application_deadline',
        'image')

        widgets = {

            'username' : forms.Select(attrs = {'class': 'form-control'}),
            'title' : forms.TextInput(attrs = {'class': 'form-control'}),
            'company_name' : forms.TextInput(attrs = {'class': 'form-control'}),
            'job_location' : forms.TextInput(attrs = {'class': 'form-control'}),
            'experience' : forms.TextInput(attrs = {'class': 'form-control'}),
            'salary' : forms.TextInput(attrs = {'class': 'form-control'}),
            'description' : forms.Textarea(attrs = {'class': 'form-control'}),
            'job_type' : forms.Select(choices= JOB_TYPE,attrs = {'class': 'form-control'}),
            'gender' : forms.Select(choices= GENDER,attrs = {'class': 'form-control'}),
            'total_vacancy' : forms.TextInput(attrs = {'class': 'form-control'}),
            'responsibilities' : forms.TextInput(attrs = {'class': 'form-control'}),
            'application_deadline' : forms.DateTimeInput(attrs = {'placeholder': '2020-12-27'}),
           # 'image' : forms.ImageInput(),

        }
class ApplyJobForm(forms.ModelForm):

    class Meta:
        model = ApplyJob
        fields = '__all__'
        
        widgets = {

            'name' : forms.TextInput(attrs = {'class': 'form-control'}),
            'email' : forms.EmailInput(attrs = {'class': 'form-control'}),
            'CV' : forms.FileInput(attrs = {'class': 'form-control'}),
        }

        labels = {
            "CV": "CV (pdf format)",
            "name": "Full Name"
        }

class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = '__all__'
        
        widgets = {

            'first_name' : forms.TextInput(attrs = {'class': 'form-control'}),
            'last_name' : forms.TextInput(attrs = {'class': 'form-control'}),
            'Email' : forms.EmailInput(attrs = {'class': 'form-control'}),
            'subject' : forms.TextInput(attrs = {'class': 'form-control'}),
            'message' : forms.Textarea(attrs = {'class': 'form-control'}),
        }

jobs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Jobs, ApplyJob, Contact
from .forms import JobForm, ApplyJobForm, ContactForm
from django.views.generic import CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'home.html')

    

class Add_Job(CreateView):
    model = Jobs
    form_class = JobForm
    template_name = 'jobs/add_job.html'
   # fields = '__all__'

def job_detail(request, id):
    job_query = get_object_or_404(Jobs, id=id)
    context = {
        'q': job_query,
    }
    return render(request, "jobs/job_detail.html", context)

def jobs_view(request):
    query = Jobs.objects.all().count()

    qs = Jobs.objects.all().order_by('-published_date')
    paginator = Paginator(qs, 3)  # Show 3 jobs per page
    page = request.GET.get('page')
    try:
        qs = paginator.page(page)
    except PageNotAnInteger:
        qs = paginator.page(1)
    except EmptyPage:
        qs = paginator.page(paginator.num_pages)

    context = {
        'query': qs,
        'job_qs': query

    }
    return render(request, 'jobs/jobs_view.html', context)

class Apply_Job(CreateView):
    model = ApplyJob
    form_class = ApplyJobForm
    template_name = 'jobs/job_apply.html'
    
 
def about_view(request):
    return render(request, 'jobs/about_us.html')

class Contact_Us(CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'jobs/contact.html'

def our_services(request):
    return render(request, 'jobs/services.html')    


user/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views import generic

class UserRegistrationView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

jobs/templates/base.html
{% load static %}


<html lang="en">
<head>
    <title>Careers </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}


</head>
<body id="top">


<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div> <!-- .site-mobile-menu -->
    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}




    <footer class="site-footer">


        <div class="container">
            <div class="row mb-5">
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Search Trending</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Graphic Design</a></li>
                        <li><a href="#">Web Developers</a></li>
                        <li><a href="#">Python</a></li>
                        <li><a href="#">HTML5</a></li>
                        <li><a href="#">CSS3</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Company</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Career</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Resources</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Support</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Support</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Terms of Service</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Contact Us</h3>
                    <div class="footer-social">
                        <a href="#"><span class="icon-facebook"></span></a>
                        <a href="#"><span class="icon-twitter"></span></a>
                        <a href="#"><span class="icon-instagram"></span></a>
                        <a href="#"><span class="icon-linkedin"></span></a>
                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="col-12">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script>
                        <i
                                class="icon-heart-o" aria-hidden="true"></i> by <a href="om" target="_blank">Careers</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>

</div>

<!-- SCRIPTS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/stickyfill.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>

<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/custom.js' %}"></script>
{% block javascripts %}{% endblock %}

</body>
</html>

jobs/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
  <!-- HOME -->
    <section class="home-section section-hero overlay bg-image"  id="home-section"
    style='background-image: url("{% static "/images/hero.jpg" %}")'>

      <div class="container">
        <div class="row align-items-center justify-content-center">
          <div class="col-md-12">
            <div class="mb-5 text-center">
              <h1 class="text-white font-weight-bold">A Powerful Career Website </h1>
              <p>Find your dream jobs in our powerful career website </p>
            </div>
            <form id="job-main-form" method="get" action="" class="search-jobs-form">
              <div class="row mb-5">
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input type="text"  id="title" name="title" class="form-control form-control-lg" placeholder=" Software Engineer ... ">
                </div>
                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                   <input    type="text" id="job_location" name="job_location" class="form-control form-control-lg" placeholder="Lahore,Pakistan">
                </div>

                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <select id="employment_status" name="employment_status" class="form-control">
                    <option>Part Time</option>
                    <option>Full Time</option>
                    <option>Freelance</option>
                  </select>
                </div>


                <div class="col-12 col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0">
                  <button type="submit" class="btn btn-primary btn-lg btn-block text-white btn-search"><span class="icon-search icon mr-2"></span>Search Job</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>


    </section>

    <section class="py-5 bg-image overlay-primary fixed overlay" style="background-image: url('images/hero_1.jpg');">
      <div class="container">
        <div class="row mb-5 justify-content-center">
          <div class="col-md-7 text-center">
            <h2 class="section-title mb-2 text-white">Careers Statistics</h2>
            <p class="lead text-white"></p>
          </div>
        </div>
        <div class="row pb-0 block__19738 section-counter">

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="56">0</strong>
            </div>
            <span class="caption">Candidates</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="3"> 0 </strong>
            </div>
            <span class="caption"> Jobs Posted</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="">0</strong>
            </div>
            <span class="caption">Jobs Filled</span>
          </div>

          <div class="col-6 col-md-6 col-lg-3 mb-5 mb-lg-0">
            <div class="d-flex align-items-center justify-content-center mb-2">
              <strong class="number" data-number="Apple">0</strong>
            </div>
            <span class="caption">Companies</span>
          </div>


        </div>
      </div>
    </section>




    <section class="site-section">
     <div class="container">



        <div class="mb-5">
        

          <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
            <div class="col-md-2">
              <a href="#"><img src="{% static 'images/featured-listing-1.jpg' %}" alt="Image" class="img-fluid"></a>
            </div>
            <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">

               Full Time

              </span>
              <h2><a href=""></a>Python Developer</h2>
              <p class="meta">Publisher: <strong>Saad Awan</strong> In: <strong>Python Category</strong></p>
            </div>
            <div class="col-md-3 text-left">
              <h3></h3>
              <span class="meta">Lahore, Pakistan</span>
            </div>
            <div class="col-md-3 text-md-right">
              <strong class="text-black">5000RS</strong>
            </div>
          </div>

        </div>



        <div class="row pagination-wrap">

          <div class="col-md-6 text-center text-md-left">
            <div class="custom-pagination ml-auto">
              
              <a  href="" class="prev">Previous</a>
              
              <div class="d-inline-block">
                Page <a href="#" class="active">5</a> of  9


              </div>
            
              <a href="" class="next">Next</a>
            
            </div>
          </div>
        </div>

      </div>
    </section>



    <section class="bg-light pt-5 testimony-full">

        <div class="owl-carousel single-carousel">


          <div class="container">
            <div class="row">
              <div class="col-lg-6 mx-auto">
                <img class="img-fluid mx-auto" src="{% static 'images/person_1.jpg' %}" alt="Image">
                <blockquote>
                  <p>&ldquo;Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae.&rdquo;</p>
                  <p><cite> &mdash; Richard Anderson</cite></p>
                </blockquote>
              </div>
            </div>
          </div>

          <div class="container">
            <div class="row">
              <div class="col-lg-6 mx-auto">
                <img class="img-fluid mx-auto" src="{% static 'images/person_2.jpg' %}" alt="Image">
                <blockquote>
                  <p>&ldquo;Soluta quasi cum delectus eum facilis recusandae nesciunt molestias accusantium libero dolores repellat id in dolorem laborum ad modi qui at quas dolorum voluptatem voluptatum repudiandae.&rdquo;</p>
                  <p><cite> &mdash; Chris Peters</cite></p>
                </blockquote>
              </div>
            </div>
          </div>

      </div>

    </section>




{% endblock %}

jobs/templates/jobs/job_apply.html
{% extends 'base.html' %}


{% block content %}

    <section class="site-section" id="next-section">
        <div class="container">


            <div class="row justify-content-center">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <center><h1 class="lead">Apply for job </h1></center>
                    <form action="" method="POST" class="" enctype="multipart/form-data">{% csrf_token %}

                        {{form.as_p}}
                        <div class="row form-group">
                            <div class="col-md-12">
                                <input type="submit" onclick="myFunction()" value="Submit"
                                       class="btn btn-primary btn-md text-white">
                            </div>
                        </div>


                    </form>
                    <script>
                        function myFunction() {
                            alert("Are you applying to this job?");
                        }
                    </script>

                </div>


            </div>

        </div>
    </section>


{% endblock %}

jobs/templates/jobs/job_detail.html
{% extends 'base.html' %}


{% load static %}




{% block content %}
    <!-- HOME -->

    <section class="section-hero overlay inner-page bg-image"
             style="background-image: url('{% static 'images/hero_1.jpg' %}')"
             id="home-section">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1 class="text-white font-weight-bold">{{ q.title }}</h1>
                </div>
            </div>
        </div>
    </section>


    <section class="site-section">
        <div class="container">
            <div class="row align-items-center mb-5">
                <div class="col-lg-8 mb-4 mb-lg-0">
                    <div class="d-flex align-items-center">
                        <div class="border p-2 d-inline-block mr-3 rounded">
                            <img src="{% static 'images/featured-listing-2.jpg' %}"
                                 alt="Free Website Template By Free-Template.co">
                        </div>
                        <div>
                            <h2>{{ q.title }}</h2>
                            <div>
                                <span class="ml-0 mr-2 mb-2"><span
                                        class="icon-briefcase mr-2"></span>{{ q.company_name }}</span>
                                <span class="m-2"><span class="icon-room mr-2"></span>{{ q.job_location }}</span>
                                <span class="m-2"><span class="icon-clock-o mr-2"></span><span
                                        class="text-primary"> {{ q.employment_status }}
                      </span></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="row">

                        <div class="col-6">
                            <a href="{% url 'jobs:apply' %}" class="btn btn-block btn-primary btn-md">Apply Now</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="mb-5">
                        <figure class="mb-5"><img src="{% static 'images/sq_img_3.jpg' %}"
                                                  alt="Free Website Template by Free-Template.co"
                                                  class="img-fluid rounded"></figure>
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                                class="icon-align-left mr-3"></span>Job
                            Description</h3>
                        <p>{{ q.description }}</p>
                    </div>
                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span
                                class="icon-rocket mr-3"></span>Responsibilities</h3>
                        <ul class="list-unstyled m-0 p-0">
                            <li class="d-flex align-items-start mb-2"><span
                                    class="icon-check_circle mr-2 text-muted"></span><span>{{ q.responsibilities }}</span>
                            </li>

                        </ul>
                    </div>

                    <div class="mb-5">
                        <h3 class="h5 d-flex align-items-center mb-4 text-primary"><span class="icon-book mr-3"></span>Experience
                        </h3>
                        <ul class="list-unstyled m-0 p-0">
                            <li class="d-flex align-items-start mb-2"><span
                                    class="icon-check_circle mr-2 text-muted"></span><span>{{ q.experience }}</span>
                            </li>

                        </ul>
                    </div>


                </div>
                <div class="col-lg-4">
                    <div class="bg-light p-3 border rounded mb-4">
                        <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Job Summary</h3>
                        <ul class="list-unstyled pl-3 mb-0">
                            <li class="mb-2"><strong class="text-black">Published
                                on:</strong> {{ q.published_on|timesince }} ago
                            </li>
                            <li class="mb-2"><strong class="text-black">Vacancy:</strong> {{ q.vacancy }}</li>
                            <li class="mb-2"><strong class="text-black">Employment
                                Status:</strong> {{ q.employment_status }}</li>
                            <li class="mb-2"><strong class="text-black">Experience:</strong> {{ q.experience }}</li>
                            <li class="mb-2"><strong class="text-black">Job Location:</strong> {{ q.job_location }}</li>
                            <li class="mb-2"><strong class="text-black">Salary:</strong> {{ q.Salary }}</li>
                            <li class="mb-2"><strong class="text-black">Gender:</strong> {{ q.gender }}</li>
                            <li class="mb-2"><strong class="text-black">Application
                                Deadline:</strong> {{ q.application_deadline }}</li>
                        </ul>
                    </div>

                    <div class="bg-light p-3 border rounded">
                        <h3 class="text-primary  mt-3 h5 pl-3 mb-3 ">Share</h3>
                        <div class="px-3">
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-facebook"></span></a>
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-twitter"></span></a>
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-linkedin"></span></a>
                            <a href="#" class="pt-3 pb-3 pr-3 pl-0"><span class="icon-pinterest"></span></a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>



{% endblock %}

jobs/templates/jobs/jobs_view.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <section class="home-section section-hero inner-page overlay bg-image"
             style="background-image: url('{% static 'images/hero_1.jpg' %}')"
             id="home-section">

        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12">
                    <div class="mb-5 text-center">
                        <h1 class="text-white font-weight-bold">Job Listings</h1>
                        <p>Find your dream jobs in our powerful career website.</p>
                    </div>
                </div>
            </div>
        </div>


    </section>





    <section class="site-section">
        <div class="container">

            <div class="row mb-5 justify-content-center">
                <div class="col-md-7 text-center">
                    <h2 class="section-title mb-2">{{job_qs}} Job Listed</h2>

                    <div class="mb-5 text-center">

                        <a href=" "
                           class="btn btn-primary border-width-2 d-none d-lg-inline-block">
                      <span class="mr-2 icon-paper-plane">

                      </span>Post a Job</a>


                    </div>


                </div>
            </div>


            <div class="mb-5">
                
                {% for q in query %}
                    <div class="row align-items-start job-item border-bottom pb-3 mb-3 pt-3">
                        <div class="col-md-2">
                            <a href=""><img class="img-fluid" src="{% static 'images/featured-listing-2.jpg' %}"
                                            alt="image"></a>
                        </div>
                        <div class="col-md-4">
              <span class="badge badge-primary px-2 py-1 mb-3">

              {{q.job_type}}

              </span>
                            <h2><a href="{% url 'jobs:job-detail' q.id %}">{{q.title}}</a></h2>

                            In: <strong>Software Engineer</strong></p>
                        </div>
                        <div class="col-md-3 text-left">
                            <h3>{{q.job_location}}</h3>
                            <span class="meta"></span>
                        </div>
                        <div class="col-md-3 text-md-right">
                            <strong class="text-black">{{q.salary}}</strong>
                        </div>
                    </div>

                {% endfor %}
            </div>


            <div class="row pagination-wrap">

                <div class="col-md-6 text-center text-md-left">
                    <div class="custom-pagination ml-auto">
                        
                            <a href="" class="prev">Previous</a>
                        
                        <div class="d-inline-block">
                            Page <a href="#" class="active">1</a> of 9


                        </div>
                        
                            <a href="" class="next">Next</a>
                        
                    </div>
                </div>
            </div>


        </div>
    </section>






{% endblock %}

jobs/templates/navbar.html
{% load static %}



<header class="site-navbar mt-3">
  <div class="container-fluid">
    <div class="row align-items-center">
      <div class="site-logo col-6"><a href="{% url 'home' %}">Jobbers</a></div>

      <nav class="mx-auto site-navigation">
        <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
    
          <li><a href="{% url 'home' %}" class="nav-link active">Home</a></li>
          <li><a href="{% url 'jobs:job-view' %}">Jobs</a></li>
          <li><a href="{% url 'jobs:about-view' %}">About</a></li>
          <li><a href="{% url 'jobs:contact-us' %}">Contact</a></li>
          <li><a href="{% url 'jobs:our-services' %}"> Services</a></li>
          
        </ul>
      </nav>

      {% if user.is_authenticated %}

      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <ul class="nav nav-tabs">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="True" aria-expanded="false">
                {{request.user.first_name}} {{request.user.last_name}}
              </a>
                <div class="dropdown-menu">
                   <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </div>
            </li>
          </ul>
        </div>
      </div>

      {% else %}

      <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
        <div class="ml-auto">
          <ul class="nav nav-tabs">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="True" aria-expanded="false">
              </a>
                <div class="dropdown-menu">
                   <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                   <a class="dropdown-item" href="{% url 'user:register' %}">Register</a>
                </div>
            </li>
          </ul>
        </div>
      </div>

{% endif %}
    </div>
  </div>
</header>